WIP: Use nom for parsing
zetok/tox pull request #51
Opened 2017-09-05 08:36 UTC by kurnevsky

2017-09-05 12:43 UTC, zetok commented
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/toxcore/common_parsers.rs, line 15 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGuSyNZnqI__EzzB7O:-KtGuSyNZnqI__EzzB7P:b-ph6s3e) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/common_parsers.rs#L15)):*
> ```Rust
> }
> 
> /// Recognizes native endian unsigned 2 bytes integer
> ```

But.. native endian shouldn't be used at all?

Most of toxcore uses BE, and (IIRC) only parts of `state_format::old` use LE.

From what I've seen, in places where BE should be used native endian was used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-05 20:02 UTC, kpp requested changes

2017-09-05 20:02 UTC, kpp commented on src/toxcore/binary_io.rs
> +        unimplemented!()
You'd better leave only declaration without definition with `unimplemented` to catch unimplemented code in compile time but not in runtime.

2017-09-05 20:02 UTC, kpp commented on src/toxcore/common_parsers.rs
> +pub fn ne_u8(i: &[u8]) -> IResult<&[u8], u8> {
What does `ne_` prefix mean?

2017-09-05 20:02 UTC, kpp commented on src/toxcore/common_parsers.rs
> +      transmute([i[0], i[1]])
Fix indent

2017-09-05 20:02 UTC, kpp commented on src/toxcore/common_parsers.rs
> +      transmute([i[0], i[1], i[2], i[3]])
Fix indent

2017-09-05 20:02 UTC, kpp commented on src/toxcore/common_parsers.rs
> +      transmute([i[0], i[1], i[2], i[3], i[4], i[5], i[6], i[7]])
Fix indent

2017-09-05 20:02 UTC, kpp commented on src/toxcore/common_parsers.rs
> +  map!(i, ne_u8, | x | { x as i8 })
Fix indent

2017-09-05 20:02 UTC, kpp commented on src/toxcore/common_parsers.rs
> +  map!(i, ne_u16, | x | { x as i16 })
Fix indent

2017-09-05 20:02 UTC, kpp commented on src/toxcore/common_parsers.rs
> +  map!(i, ne_u32, | x | { x as i32 })
Fix indent

2017-09-05 20:02 UTC, kpp commented on src/toxcore/common_parsers.rs
> +  map!(i, ne_u64, | x | { x as i64 })
Fix indent

2017-09-05 20:02 UTC, kpp commented on src/toxcore/binary_io.rs
>                  debug!("Can't parse bytes. Error: {:?}", err);
`error!`

2017-09-05 20:02 UTC, kpp commented on src/toxcore/packet_kind.rs
> +    // fn parse_bytes(bytes: &[u8]) -> ParseResult<Self> {
Reimplement function `parse_bytes`.

2017-09-05 20:02 UTC, kpp commented on src/toxcore/dht.rs
> +    // fn parse_bytes(bytes: &[u8]) -> ParseResult<Self> {
Reimplement function `parse_bytes`.

2017-09-05 20:02 UTC, kpp commented on src/toxcore/dht.rs
> +    // fn parse_bytes(bytes: &[u8]) -> ParseResult<Self> {
Reimplement function `parse_bytes`.

2017-09-05 20:02 UTC, kpp commented on src/toxcore/dht.rs
> +    // fn parse_bytes(bytes: &[u8]) -> ParseResult<Self> {
Reimplement function `parse_bytes`.

2017-09-05 20:02 UTC, kpp commented on src/toxcore/toxid.rs
> +    checksum: map!(take!(2), |bytes| { [bytes[0], bytes[1]] }) >>
Should we create a named const `CHECKSUMBYTES = 2`?

2017-09-05 20:02 UTC, kpp commented on src/toxcore/state_format/old.rs
> +    // fn parse_bytes(bytes: &[u8]) -> ParseResult<Self> {
Reimplement function `parse_bytes`.

2017-09-05 20:02 UTC, kpp commented on src/toxcore/state_format/old.rs
> +    // fn parse_bytes(bytes: &[u8]) -> ParseResult<Self> {
Reimplement function `parse_bytes`.

2017-09-05 20:02 UTC, kpp commented on src/toxcore/state_format/old.rs
> +    // fn parse_bytes(bytes: &[u8]) -> ParseResult<Self> {
Reimplement function `parse_bytes`.

2017-09-05 20:02 UTC, kpp commented on src/toxcore/state_format/old.rs
> +    (FriendState {
This is amazing :+1:

2017-09-05 20:02 UTC, kpp commented on src/toxcore/state_format/old.rs
> +    // fn parse_bytes(bytes: &[u8]) -> ParseResult<Self> {
Reimplement function `parse_bytes`.

2017-09-05 20:37 UTC, kurnevsky commented
*[src/toxcore/binary_io.rs, line 38 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTW-r1-38:-KtIkQeck4Ytwum3-LfP:b-42jvjd) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/binary_io.rs#L38)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

You'd better leave only declaration without definition with `unimplemented` to catch unimplemented code in compile time but not in runtime.
</blockquote></details>

Yeah, I've used unimplemented! just because it's WIP and I need to check how does my code compile. Final version won't have this definition.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-05 20:41 UTC, kurnevsky commented
*[src/toxcore/common_parsers.rs, line 15 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGuSyNZnqI__EzzB7O:-KtIlC0NMJfFRs84s8XP:b-tbv65c) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/common_parsers.rs#L15)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

But.. native endian shouldn't be used at all?

Most of toxcore uses BE, and (IIRC) only parts of `state_format::old` use LE.

From what I've seen, in places where BE should be used native endian was used.
</blockquote></details>

I added native endian parsers because we parse random id as native endian int. If we change it to be or le these parsers won't be necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-05 20:42 UTC, kurnevsky commented
*[src/toxcore/common_parsers.rs, line 7 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTX-r1-7:-KtIlePanNNjPzv6Da_y:b-vq0kql) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/common_parsers.rs#L7)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

What does `ne_` prefix mean?
</blockquote></details>

native endian, like be_/le_ prefixes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-05 21:36 UTC, kpp commented
Review status: 0 of 10 files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

*[src/toxcore/common_parsers.rs, line 7 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTX-r1-7:-KtIxa5DwjOrFUYIPG5N:bvnbkvz) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/common_parsers.rs#L7)):*
<details><summary><i>Previously, kurnevsky (Evgeny Kurnevsky) wrote…</i></summary><blockquote>

native endian, like be_/le_ prefixes
</blockquote></details>

you have to comment it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-06 09:32 UTC, kpp commented
@kurnevsky I may help you with your code if you don't have enough time.

2017-09-06 19:42 UTC, kurnevsky commented
@kpp I think I can continue at the weekend. But I don't mind if you update something :)

2017-09-09 10:38 UTC, kurnevsky commented
*[src/toxcore/binary_io.rs, line 47 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTW-r1-47:-KtaCwWNxzFdKnLIozqt:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/binary_io.rs#L47)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

`error!`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 10:38 UTC, kurnevsky commented
*[src/toxcore/common_parsers.rs, line 22 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTX-r1-22:-KtaD10wRBWSkU5oK9NX:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/common_parsers.rs#L22)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Fix indent
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 10:38 UTC, kurnevsky commented
*[src/toxcore/common_parsers.rs, line 35 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTX-r1-35:-KtaD27b09BAsvpDwxVC:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/common_parsers.rs#L35)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Fix indent
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 10:38 UTC, kurnevsky commented
*[src/toxcore/common_parsers.rs, line 48 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTX-r1-48:-KtaD3gKHZy1KkVq9-76:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/common_parsers.rs#L48)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Fix indent
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 10:38 UTC, kurnevsky commented
*[src/toxcore/common_parsers.rs, line 57 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTX-r1-57:-KtaD56If9AuGxNhRzpE:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/common_parsers.rs#L57)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Fix indent
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 10:38 UTC, kurnevsky commented
*[src/toxcore/common_parsers.rs, line 63 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTX-r1-63:-KtaD6rZekbcF_RXcsaD:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/common_parsers.rs#L63)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Fix indent
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 10:39 UTC, kurnevsky commented
*[src/toxcore/common_parsers.rs, line 69 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTX-r1-69:-KtaD8FCXGNShnBhsJf5:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/common_parsers.rs#L69)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Fix indent
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 10:39 UTC, kurnevsky commented
*[src/toxcore/common_parsers.rs, line 75 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTX-r1-75:-KtaD9lR84Hd6j7osVzQ:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/common_parsers.rs#L75)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Fix indent
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 10:39 UTC, kurnevsky commented
*[src/toxcore/packet_kind.rs, line 84 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhT_-r1-84:-KtaDFciSz4cvv9-n9vq:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/packet_kind.rs#L84)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Reimplement function `parse_bytes`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 10:43 UTC, kurnevsky commented
*[src/toxcore/dht.rs, line 169 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTZ-r1-169:-KtaEC7j6JDRG9g_mB4I:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/dht.rs#L169)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Reimplement function `parse_bytes`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 10:43 UTC, kurnevsky commented
*[src/toxcore/dht.rs, line 387 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTZ-r1-387:-KtaEFQ_8l1xxRCebdqU:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/dht.rs#L387)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Reimplement function `parse_bytes`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 10:44 UTC, kurnevsky commented
*[src/toxcore/dht.rs, line 513 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTZ-r1-513:-KtaEJjtUvacAgK7iRBa:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/dht.rs#L513)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Reimplement function `parse_bytes`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 10:55 UTC, kpp commented
Review status: 0 of 10 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[src/toxcore/common_parsers.rs, line 48 at r2](https://reviewable.io:443/reviews/zetok/tox/51#-KtaFTutIv9ZxWdAnDSt:-KtaFTuu-LHge-54ABce:be4ozq6) ([raw file](https://github.com/zetok/tox/blob/7d91b9f637da25796a6f0d7122067a0112c74a40/src/toxcore/common_parsers.rs#L48)):*
> ```Rust
>     } else {
>         let res = unsafe {
>             transmute([i[0], i[1], i[2], i[3], i[4], i[5], i[6], i[7]])
> ```

Is there any way to fix this bloatcode?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 11:00 UTC, kpp commented
Reviewed 6 of 9 files at r2.
Review status: 6 of 10 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 11:10 UTC, kurnevsky commented
*[src/toxcore/common_parsers.rs, line 48 at r2](https://reviewable.io:443/reviews/zetok/tox/51#-KtaFTutIv9ZxWdAnDSt:-KtaIZJ-98MyEzo0cc6v:b6t30k8) ([raw file](https://github.com/zetok/tox/blob/7d91b9f637da25796a6f0d7122067a0112c74a40/src/toxcore/common_parsers.rs#L48)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Is there any way to fix this bloatcode?
</blockquote></details>

I've written it by analogy with le_/be_ functions from nom. I didn't try to improve it. Btw, I created pr to nom but it seems the author wasn't interested in native endianness: https://github.com/Geal/nom/pull/541

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 19:23 UTC, kurnevsky commented
Reimplemented all parsers, finally. But tests don't compile yet.

2017-09-09 22:00 UTC, kpp commented
Reviewed 1 of 10 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-09 22:01 UTC, kpp commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51#-:-KtceEiMnFk1OW77KVml:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-09-09 22:17 UTC, kpp requested changes

2017-09-09 22:17 UTC, kpp commented on src/toxcore/dht.rs
> +from_bytes!(Ipv4Addr, map!(take!(4), |bytes| Ipv4Addr::new(bytes[0], bytes[1], bytes[2], bytes[3])));
Can you use impl `From<[u8; 4]>`?

2017-09-09 22:17 UTC, kpp commented on src/toxcore/dht.rs
> +from_bytes!(Ipv6Addr, map!(count!(le_u16, 8), |v| Ipv6Addr::new(v[0], v[1], v[2], v[3], v[4], v[5], v[6], v[7])));
Can you use impl `From<[u16; 8]>`?

2017-09-09 22:17 UTC, kpp commented on src/toxcore/common_parsers.rs
> +            transmute([i[0], i[1], i[2], i[3]])
see examples from [Rust doc](https://doc.rust-lang.org/1.14.0/book/casting-between-types.html#transmute). You may make the code simpler by using `mem::transmute::<[u8; 4], u32>(a)`

2017-09-09 22:17 UTC, kpp commented on src/toxcore/toxid.rs
> +from_bytes!(NoSpam, map!(take!(NOSPAMBYTES), |bytes| { NoSpam([bytes[0], bytes[1], bytes[2], bytes[3]]) }));
`&bytes[..NOSPAMBYTES]`?

2017-09-15 16:12 UTC, kpp commented
@kurnevsky will you continue working on this PR on weekend?

2017-09-16 19:41 UTC, kurnevsky commented
Fixed tests compilation. But some of them are broken...

2017-09-17 08:51 UTC, kurnevsky commented
It seems that tests tox_codec_decode_test and nonce_parse_bytes_test weren't correct.

2017-09-17 08:55 UTC, kurnevsky commented
public_key_parse_bytes_test and secret_key_parse_bytes_test aswell.

2017-09-17 09:59 UTC, kpp commented
Also mark `ERROR:tox::toxcore::binary_io: Can't parse bytes. Error: Switch` as warning. No one loves error spam.

2017-09-17 10:21 UTC, kurnevsky commented
Why friends_parse_bytes_test checks that friends should be parsed even with trash in the end?

2017-09-19 12:12 UTC, zetok commented
>Why friends_parse_bytes_test checks that friends should be parsed even with trash in the end?

That part of the test checks whether only `Friends` amount of bytes are parsed, and that the following bytes after `Friends` are all present after `Friends` parsing is done. Whatever data is after `Friends` bytes, it shouldn't matter to the `Firends` parsing fn, and should be passed on.

2017-09-21 19:51 UTC, kurnevsky commented
@zetok there is no size specified for friends struct, it uses parse_bytes_multiple: https://github.com/zetok/tox/blob/master/src/toxcore/state_format/old.rs#L880
But here https://github.com/zetok/tox/blob/master/src/toxcore_tests/state_format_old_tests.rs#L348 you check that it should stop parsing when it can't parse anymore.
I used many0 parser here and it fails if it can't parse all input.

2017-09-22 07:02 UTC, zetok commented
@kurnevsky 
>@zetok there is no size specified for friends struct, it uses parse_bytes_multiple: https://github.com/zetok/tox/blob/master/src/toxcore/state_format/old.rs#L880

Actually, the "specified" size is multiples of `FRIENDSTATEBYTES`. I guess that part of the test is somewhat redundant.

2017-09-22 08:54 UTC, kurnevsky commented
*[src/toxcore/common_parsers.rs, line 56 at r3](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTX-r3-56:-KucmleZGhZ5RdR6wPqD:b-dysb52) ([raw file](https://github.com/zetok/tox/blob/9439d25fb2e27d68f56187fbb22bbb9e2eea2964/src/toxcore/common_parsers.rs#L56)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

see examples from [Rust doc](https://doc.rust-lang.org/1.14.0/book/casting-between-types.html#transmute). You may make the code simpler by using `mem::transmute::<[u8; 4], u32>(a)`
</blockquote></details>

Yeah, but I can't convert &[u8] to [u8; 4].

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 08:55 UTC, kurnevsky commented
*[src/toxcore/common_parsers.rs, line 7 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTX-r1-7:-KtaHw0zGeCOwqgQ-zL2:bfbn8qx) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/common_parsers.rs#L7)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

you have to comment it
</blockquote></details>

It's already commented in other functions since only for them this prefix matters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 08:56 UTC, kurnevsky commented
*[src/toxcore/dht.rs, line 223 at r3](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTZ-r3-223:-KucnGEO7KxmPwdElX-k:b-avg8fu) ([raw file](https://github.com/zetok/tox/blob/9439d25fb2e27d68f56187fbb22bbb9e2eea2964/src/toxcore/dht.rs#L223)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Can you use impl `From<[u8; 4]>`?
</blockquote></details>

The same here. I can't becouse I have only &[u8].

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 08:56 UTC, kurnevsky commented
*[src/toxcore/dht.rs, line 228 at r3](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTZ-r3-228:-KucnNnL23wOLg816XM7:b-avg8fu) ([raw file](https://github.com/zetok/tox/blob/9439d25fb2e27d68f56187fbb22bbb9e2eea2964/src/toxcore/dht.rs#L228)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Can you use impl `From<[u16; 8]>`?
</blockquote></details>

The same here. I can't becouse I have only &[u8].

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 08:58 UTC, kurnevsky commented
*[src/toxcore/toxid.rs, line 112 at r3](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTb-r3-112:-KucnaxyP9n4pobgiHWt:brczuki) ([raw file](https://github.com/zetok/tox/blob/9439d25fb2e27d68f56187fbb22bbb9e2eea2964/src/toxcore/toxid.rs#L112)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

`&bytes[..NOSPAMBYTES]`?
</blockquote></details>

&[u8] can't be converted to [u8; NOSPAMBYTES]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 08:58 UTC, kurnevsky commented
*[src/toxcore/state_format/old.rs, line 381 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTa-r1-381:-KucnltuFTn5oCG19kwp:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/state_format/old.rs#L381)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Reimplement function `parse_bytes`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 08:58 UTC, kurnevsky commented
*[src/toxcore/state_format/old.rs, line 550 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTa-r1-550:-KucnnTMxYYyV15_LgMi:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/state_format/old.rs#L550)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Reimplement function `parse_bytes`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 08:58 UTC, kurnevsky commented
*[src/toxcore/state_format/old.rs, line 1105 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTa-r1-1105:-KucnqGP5aFPM3g4GwsO:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/state_format/old.rs#L1105)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Reimplement function `parse_bytes`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 08:58 UTC, kurnevsky commented
*[src/toxcore/state_format/old.rs, line 1345 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTa-r1-1345:-KucnuAds8heDEWy0KCI:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/state_format/old.rs#L1345)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Reimplement function `parse_bytes`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 14:09 UTC, kpp commented
Reviewed 18 of 18 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/toxcore/dht.rs, line 228 at r3](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTZ-r3-228:-KudoxSOWgIPC4lMAUyU:boaihbi) ([raw file](https://github.com/zetok/tox/blob/9439d25fb2e27d68f56187fbb22bbb9e2eea2964/src/toxcore/dht.rs#L228)):*
<details><summary><i>Previously, kurnevsky (Evgeny Kurnevsky) wrote…</i></summary><blockquote>

The same here. I can't becouse I have only &[u8].
</blockquote></details>

https://stackoverflow.com/a/37682288  No?

```
fn by_value(s: [u8; 4]) {
    println!("s: {:?}", s);
}

fn by_ref(s: &[u8]) {
    let mut a: [u8; 4] = Default::default();
    a.clone_from_slice(&s[..4]);
    by_value(a);
}

fn main() {
    let s = [1, 2, 3, 4, 5, 6, 7, 8];
    by_ref(&s);
}
```

---

*[src/toxcore/iresult_expect.rs, line 27 at r4](https://reviewable.io:443/reviews/zetok/tox/51#-Kudsjg8x9F1myKgEwEo:-Kudsjg8x9F1myKgEwEp:bjjk9b0) ([raw file](https://github.com/zetok/tox/blob/4808e06134c4b728723fb6e5d22ae72a0c0791d0/src/toxcore/iresult_expect.rs#L27)):*
> ```Rust
> /// Adds an expect method.
> pub trait Expect<T> {
>     /// Unwraps a result, yielding the content.
> ```

You'd better not put this in `toxcore/` root. Plz organize your files

---

*[src/toxcore/state_format/old.rs, line 1876 at r4](https://reviewable.io:443/reviews/zetok/tox/51#-KudtLaTHdQpgddeXSg_:-KudtLaTHdQpgddeXSga:bozlb7s) ([raw file](https://github.com/zetok/tox/blob/a1cf4300625299505191a899c7a17b1cdfd6f4c4/src/toxcore/state_format/old.rs#L1876)):*
> ```Rust
> // State::is_state()
> 
> #[test]
> ```

Why did you remove this test?

---

*[src/toxcore_tests/test_macros.rs, line 21 at r4](https://reviewable.io:443/reviews/zetok/tox/51#-Kudu3pxUAieD7ezGgUP:-Kudu3pyIHZTwV1GokNW:brqbq5v) ([raw file](https://github.com/zetok/tox/blob/4808e06134c4b728723fb6e5d22ae72a0c0791d0/src/toxcore_tests/test_macros.rs#L21)):*
> ```Rust
> 
> 
> //! File with testing macros. **Use only in tests!**
> ```

Do we need these macros?

---

*[tests/load-state-format-old.rs, line 28 at r4](https://reviewable.io:443/reviews/zetok/tox/51#-KuduUt4OO9rxlkHihTQ:-KuduUt5DHnEKm0weCKl:b-1qzl73) ([raw file](https://github.com/zetok/tox/blob/4808e06134c4b728723fb6e5d22ae72a0c0791d0/tests/load-state-format-old.rs#L28)):*
> ```Rust
> fn test_state_format_old_load() {
>     let bytes = include_bytes!("state-format-old-data/profile-no-friends.tox");
>     let profile = State::from_bytes(bytes).expect("Works.");
> ```

```
IResult::Error(e) => panic!("{}: {}", e.description(), err)
```

Works?

---

*[tests/serialize-deserialize-state-format-old.rs, line 35 at r4](https://reviewable.io:443/reviews/zetok/tox/51#-Kudud_xsvwH9NEUUeor:-Kudud_xsvwH9NEUUeos:b-iokn30) ([raw file](https://github.com/zetok/tox/blob/4808e06134c4b728723fb6e5d22ae72a0c0791d0/tests/serialize-deserialize-state-format-old.rs#L35)):*
> ```Rust
> fn test_state_format_to_and_from_bytes() {
>     let bytes = include_bytes!("state-format-old-data/profile-with-contacts.tox");
>     let profile_b = State::from_bytes(bytes).expect("Works.").to_bytes();
> ```

Also would you please fix `"Works"` here. Thank you

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 14:33 UTC, kurnevsky commented
*[src/toxcore/iresult_expect.rs, line 27 at r4](https://reviewable.io:443/reviews/zetok/tox/51#-Kudsjg8x9F1myKgEwEo:-Kue-LgmL_VMPPGdNX4H:b85n1l4) ([raw file](https://github.com/zetok/tox/blob/4808e06134c4b728723fb6e5d22ae72a0c0791d0/src/toxcore/iresult_expect.rs#L27)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

You'd better not put this in `toxcore/` root. Plz organize your files
</blockquote></details>

I put it here because there are tests in toxcore that use expect (can't import toxcore_tests from toxcore).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 14:36 UTC, kurnevsky commented
*[src/toxcore/state_format/old.rs, line 1876 at r4](https://reviewable.io:443/reviews/zetok/tox/51#-KudtLaTHdQpgddeXSg_:-Kue-ycJwFJLQCtjXInv:bc4rikf) ([raw file](https://github.com/zetok/tox/blob/a1cf4300625299505191a899c7a17b1cdfd6f4c4/src/toxcore/state_format/old.rs#L1876)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Why did you remove this test?
</blockquote></details>

I didn't, it's still there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 14:36 UTC, kurnevsky commented
*[src/toxcore_tests/test_macros.rs, line 21 at r4](https://reviewable.io:443/reviews/zetok/tox/51#-Kudu3pxUAieD7ezGgUP:-Kue0EziwgToXXd3zDpk:bea7kz7) ([raw file](https://github.com/zetok/tox/blob/4808e06134c4b728723fb6e5d22ae72a0c0791d0/src/toxcore_tests/test_macros.rs#L21)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Do we need these macros?
</blockquote></details>

Some tests use them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 15:07 UTC, kpp commented
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/toxcore/iresult_expect.rs, line 27 at r4](https://reviewable.io:443/reviews/zetok/tox/51#-Kudsjg8x9F1myKgEwEo:-Kue74v1UFBgccZHAORb:bib4ua4) ([raw file](https://github.com/zetok/tox/blob/4808e06134c4b728723fb6e5d22ae72a0c0791d0/src/toxcore/iresult_expect.rs#L27)):*
<details><summary><i>Previously, kurnevsky (Evgeny Kurnevsky) wrote…</i></summary><blockquote>

I put it here because there are tests in toxcore that use expect (can't import toxcore_tests from toxcore).
</blockquote></details>

You may put it into binary io, don't you?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 16:38 UTC, kurnevsky commented
*[src/toxcore/iresult_expect.rs, line 27 at r4](https://reviewable.io:443/reviews/zetok/tox/51#-Kudsjg8x9F1myKgEwEo:-KueS4oQ5xKaAN7BeFuc:b-896fix) ([raw file](https://github.com/zetok/tox/blob/4808e06134c4b728723fb6e5d22ae72a0c0791d0/src/toxcore/iresult_expect.rs#L27)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

You may put it into binary io, don't you?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 16:39 UTC, kurnevsky commented
*[tests/load-state-format-old.rs, line 28 at r4](https://reviewable.io:443/reviews/zetok/tox/51#-KuduUt4OO9rxlkHihTQ:-KueSFgZk7D2j_0UKPel:b-up2m7h) ([raw file](https://github.com/zetok/tox/blob/4808e06134c4b728723fb6e5d22ae72a0c0791d0/tests/load-state-format-old.rs#L28)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

```
IResult::Error(e) => panic!("{}: {}", e.description(), err)
```

Works?
</blockquote></details>

What do you mean here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 16:39 UTC, kurnevsky commented
*[tests/serialize-deserialize-state-format-old.rs, line 35 at r4](https://reviewable.io:443/reviews/zetok/tox/51#-Kudud_xsvwH9NEUUeor:-KueSQAyalWXzz_ba5l5:b-896fix) ([raw file](https://github.com/zetok/tox/blob/4808e06134c4b728723fb6e5d22ae72a0c0791d0/tests/serialize-deserialize-state-format-old.rs#L35)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Also would you please fix `"Works"` here. Thank you
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 16:45 UTC, kurnevsky commented
*[tests/load-state-format-old.rs, line 28 at r4](https://reviewable.io:443/reviews/zetok/tox/51#-KuduUt4OO9rxlkHihTQ:-KueTjEXHsW4TTLFTuSh:b-896fix) ([raw file](https://github.com/zetok/tox/blob/4808e06134c4b728723fb6e5d22ae72a0c0791d0/tests/load-state-format-old.rs#L28)):*
<details><summary><i>Previously, kurnevsky (Evgeny Kurnevsky) wrote…</i></summary><blockquote>

What do you mean here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-22 18:06 UTC, kpp commented
You may run `cargo coverage`(install it with `cargo install cargo-travis`) and check missing tests for your code. Because we get `-0.2%` coverage. But it is optional. If you are tired and want to merge, just tell me))

---

Reviewed 10 of 11 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51#-:-Kueki4QP3FwYYqsgkfU:bfbsuxy)*
<!-- Sent from Reviewable.io -->

2017-09-22 18:14 UTC, kurnevsky commented
I think it's because I removed some covered code so ratio covered/uncovered was changed.

2017-09-22 18:24 UTC, kpp commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51#-:-KuepGOp8ktqldJIZv6n:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-09-22 18:24 UTC, kpp approved these changes

2017-09-23 21:34 UTC, zetok commented
Reviewed 1 of 5 files at r3, 3 of 7 files at r6.
Review status: 16 of 19 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/toxcore/dht.rs, line 361 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KukKky3xYeGhrpuINmK:-KukKky4vId21p4Hmxi6:byoqe6h) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/dht.rs#L361)):*
> ```Rust
> }
> 
> // parse bytes as IPv4
> ```

This comment is rather misleading if someone doesn't look at the code below – instead of saying that bytes are parsed as an IPv4 address, it should say that bytes are parsed as an IPv4 type of PackedNode: `Parse bytes as an IPv4 PackedNode`.

Same goes for the comment for corresponding IPv6 function comment.

---

*[src/toxcore/dht.rs, line 362 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KukJoHHVVjLzDMM1GKM:-KukJoHI1f9mvP70SYPS:b-pevc5f) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/dht.rs#L362)):*
> ```Rust
> 
> // parse bytes as IPv4
> named_args!(as_ipv4(iptype: IpType) <PackedNode>, do_parse!(
> ```

I think that the function name should better reflect what the function is for, in this case it probably should be renamed to `as_ipv4_packed_node`. Since there are only 2 places where function is called, there's no real benefit in shortening its name, and there's a minus side of making it a bit more confusing by obfuscating its name.

Earlier this function name was inside of the parsing function, and as the function could be used only inside the parsing function having short name was still fine. As it is now accessible for use by more than just the parsing function, it should have a better name.

Also, since function is used only in the FromBytes implementation of PackedNode the comment above the function should state that it is intended to be used only there.

Same goes for the corresponding IPv6 function name.

---

*[src/toxcore/dht.rs, line 755 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KukQ597j1SSib01iiHt:-KukQ598d9etHl7huOH0:bfmffnd) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/dht.rs#L755)):*
> ```Rust
> /// De-serialize bytes into `DhtPacket`.
> from_bytes!(DhtPacket, do_parse!(
>     packet_type: call!(PacketKind::parse_bytes) >>
> ```

`cond_reduce!` (or better fitting macro) should be used to make sure that `packet_type` is one of 4 first `PacketKind`s – `DhtPacket` is valid only when it claims to contain one of those, otherwise the packet is invalid.

The previously existing macro did that check:

```rust
        match packet_type {
            PacketKind::PingReq | PacketKind::PingResp |
            PacketKind::GetN | PacketKind::SendN => {},
            p => {
                return parse_error!("Failed: not a DHT packet! Packet: {:?}", p)
            },
```

Also, since tests apparently didn't catch this case, a test should be added (or existing one should be extended).

---

*[src/toxcore/dht_node.rs, line 697 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KukSqwNKlE16P7SsTQd:-KukSqwNKlE16P7SsTQe:b-rs2juw) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/dht_node.rs#L697)):*
> ```Rust
>         fn with_dp(dp: DhtPacket, kind: u8) -> TestResult {
>             // need an invalid PacketKind for DhtPacket
>             if PacketKind::parse_bytes(&[kind]).is_done() {
> ```

Doesn't this invalidate the test?

---

*[src/toxcore/toxid.rs, line 257 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTb-r1-257:-KukUYbayN8FV5uqrX3o:bv2bdfw) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/toxid.rs#L257)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Should we create a named const `CHECKSUMBYTES = 2`?
</blockquote></details>

Probably. @kurnevsky mind adding?

---

*[src/toxcore/toxid.rs, line 112 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KukUITyACrCL2d3yd6n:-KukUITz4kvSvtDAZqXn:b3ptfjl) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/toxid.rs#L112)):*
> ```Rust
> }
> 
> from_bytes!(NoSpam, map!(take!(NOSPAMBYTES), |bytes| { NoSpam([bytes[0], bytes[1], bytes[2], bytes[3]]) }));
> ```

Curly brackets (`{}`) aren't needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-24 14:31 UTC, zetok commented
The second commit (caeede48d031bf22d0716dc5a97f7191895388de) can be squashed..?

---

Reviewed 1 of 18 files at r4, 6 of 11 files at r5, 2 of 7 files at r6.
Review status: 17 of 19 files reviewed at latest revision, 16 unresolved discussions.

---

*[src/toxcore/binary_io.rs, line 42 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoDZQxJskQj_0tABU1:-KuoDZQxJskQj_0tABU2:boqfcv2) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/binary_io.rs#L42)):*
> ```Rust
>     /// De-serialize as many entities from bytes as posible.
>     /// Note that even if `Vec<_>` is returned, it still can be empty.
>     named!(parse_bytes_multiple<&[u8], Vec<Self>>, many0!(Self::parse_bytes));
> ```

```
warning: missing documentation for a trait method
  --> src/toxcore/binary_io.rs:42:5
   |
42 |     named!(parse_bytes_multiple<&[u8], Vec<Self>>, many0!(Self::parse_bytes));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: lint level defined here
  --> src/lib.rs:169:8
   |
169| #[warn(missing_docs)]
   |        ^^^^^^^^^^^^
   = note: this error originates in a macro outside of the current crate
```

Perhaps add `#[allow(missing_docs)]` above this, along with a comment why it's needed.

---

*[src/toxcore/binary_io.rs, line 46 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoDsS7NaxVSbe5IGXq:-KuoDsS7NaxVSbe5IGXr:bpgw62j) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/binary_io.rs#L46)):*
> ```Rust
>     /// De-serialize exact `times` entities from bytes.
>     /// Note that even if `Vec<_>` is returned, it still can be empty.
>     named_args!(parse_bytes_multiple_n(times: usize) <Vec<Self>>, many_m_n!(times, times, Self::parse_bytes));
> ```

```
warning: missing documentation for a trait method
  --> src/toxcore/binary_io.rs:46:5
   |
46 |     named_args!(parse_bytes_multiple_n(times: usize) <Vec<Self>>, many_m_n!(times, times, Self::parse_bytes));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro outside of the current crate
```

Same as above.

---

*[src/toxcore/state_format/old.rs, line 24 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoCw2PH7GZ6GpC18JF:-KuoCw2PH7GZ6GpC18JG:b-k2h27k) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/state_format/old.rs#L24)):*
> ```Rust
> 
> use std::default::Default;
> use byteorder::{BigEndian, ByteOrder, LittleEndian, WriteBytesExt};
> ```

```
warning: unused import: `ByteOrder`, #[warn(unused_imports)] on by default
  --> src/toxcore/state_format/old.rs:24:28
   |
24 | use byteorder::{BigEndian, ByteOrder, LittleEndian, WriteBytesExt};
   |                            ^^^^^^^^^
```

Still used in tests, but when building without tests produces a warning

---

*[src/toxcore/state_format/old.rs, line 1173 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoCX9684KjgjYVmZYY:-KuoCX970WrWNOmPQWpt:b-lk87av) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/state_format/old.rs#L1173)):*
> ```Rust
> 
> /// Length of `State` header.
> const STATE_HEAD_LEN: usize = 8;
> ```

```
warning: constant item is never used: `STATE_HEAD_LEN`, #[warn(dead_code)] on by default
    --> src/toxcore/state_format/old.rs:1173:1
     |
1173 | const STATE_HEAD_LEN: usize = 8;
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Since it's still used in tests, add `#[cfg(test)]` above it.

---

*[src/toxcore/state_format/old.rs, line 1354 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-Kuo9iBUSmM7EXVNBj67:-Kuo9iBUSmM7EXVNBj68:b-kxsp1g) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/state_format/old.rs#L1354)):*
> ```Rust
> 
> #[test]
> #[cfg(test)] // ← https://github.com/rust-lang/rust/issues/16688
> ```

Since test macro is no longer used in the fn, the `cfg` line can be removed.

---

*[src/toxcore/state_format/old.rs, line 1571 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoAcNOKXU0bewKfcFx:-KuoAcNPH1dgdEPlWRhY:b-e6yfkp) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/state_format/old.rs#L1571)):*
> ```Rust
> 
> #[test]
> #[cfg(test)] // ← https://github.com/rust-lang/rust/issues/16688
> ```

Same as above, line can be removed.

---

*[src/toxcore/state_format/old.rs, line 1675 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoBQjHIK66Nb-byXM7:-KuoBQjHIK66Nb-byXM8:b-e6yfkp) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/state_format/old.rs#L1675)):*
> ```Rust
> 
> #[test]
> #[cfg(test)] // ← https://github.com/rust-lang/rust/issues/16688
> ```

Same as above, line can be removed.

---

*[src/toxcore_tests/state_format_old_tests.rs, line 335 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoG_sj0nviPEjUzI0T:-KuoG_sj0nviPEjUzI0U:b-ay04fy) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore_tests/state_format_old_tests.rs#L335)):*
> ```Rust
> #[test]
> fn friends_parse_bytes_test() {
>     fn with_friend_state(fs: Vec<FriendState>, randb: Vec<u8>) {
> ```

```
warning: unused variable: `randb`, #[warn(unused_variables)] on by default
   --> src/toxcore_tests/state_format_old_tests.rs:335:48
    |
335 |     fn with_friend_state(fs: Vec<FriendState>, randb: Vec<u8>) {
    |                                                ^^^^^
```

That part of the test was removed, so this also needs to go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51#-:-KuoI2VUXpd96baJJJFW:b-m17m8e)*
<!-- Sent from Reviewable.io -->

2017-09-24 15:01 UTC, kpp commented
Reviewed 2 of 7 files at r6.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[src/toxcore/binary_io.rs, line 42 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoDZQxJskQj_0tABU1:-KuoNOjQV2biBbRAh1zL:b-tuaq8m) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/binary_io.rs#L42)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

```
warning: missing documentation for a trait method
  --> src/toxcore/binary_io.rs:42:5
   |
42 |     named!(parse_bytes_multiple<&[u8], Vec<Self>>, many0!(Self::parse_bytes));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: lint level defined here
  --> src/lib.rs:169:8
   |
169| #[warn(missing_docs)]
   |        ^^^^^^^^^^^^
   = note: this error originates in a macro outside of the current crate
```

Perhaps add `#[allow(missing_docs)]` above this, along with a comment why it's needed.
</blockquote></details>

Or you may try `named_attr` to create function with docs

---

*[src/toxcore/state_format/old.rs, line 1173 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoCX9684KjgjYVmZYY:-KuoOiH0bhRun8sl_YoR:b-szq1xg) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/state_format/old.rs#L1173)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

```
warning: constant item is never used: `STATE_HEAD_LEN`, #[warn(dead_code)] on by default
    --> src/toxcore/state_format/old.rs:1173:1
     |
1173 | const STATE_HEAD_LEN: usize = 8;
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Since it's still used in tests, add `#[cfg(test)]` above it.
</blockquote></details>

Well, if it is used in tests only, you may move it in tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 19:09 UTC, kurnevsky commented
*[src/toxcore/dht.rs, line 755 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KukQ597j1SSib01iiHt:-Kuz_xxOdliJyKY3lDy8:bk6eqim) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/dht.rs#L755)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`cond_reduce!` (or better fitting macro) should be used to make sure that `packet_type` is one of 4 first `PacketKind`s – `DhtPacket` is valid only when it claims to contain one of those, otherwise the packet is invalid.

The previously existing macro did that check:

```rust
        match packet_type {
            PacketKind::PingReq | PacketKind::PingResp |
            PacketKind::GetN | PacketKind::SendN => {},
            p => {
                return parse_error!("Failed: not a DHT packet! Packet: {:?}", p)
            },
```

Also, since tests apparently didn't catch this case, a test should be added (or existing one should be extended).
</blockquote></details>

Somehow missed that part.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 19:11 UTC, kurnevsky commented
*[src/toxcore/dht.rs, line 755 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KukQ597j1SSib01iiHt:-KuzaQp4u8i3ox3mEN5v:b-896fix) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/dht.rs#L755)):*
<details><summary><i>Previously, kurnevsky (Evgeny Kurnevsky) wrote…</i></summary><blockquote>

Somehow missed that part.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 19:12 UTC, kurnevsky commented
*[src/toxcore/dht_node.rs, line 697 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KukSqwNKlE16P7SsTQd:-KuzaelqiVc3HTwNuJJ-:b-896fix) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/dht_node.rs#L697)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Doesn't this invalidate the test?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 19:13 UTC, kurnevsky commented
*[src/toxcore_tests/state_format_old_tests.rs, line 335 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoG_sj0nviPEjUzI0T:-Kuzarh9fmPidQvx_teL:b-896fix) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore_tests/state_format_old_tests.rs#L335)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

```
warning: unused variable: `randb`, #[warn(unused_variables)] on by default
   --> src/toxcore_tests/state_format_old_tests.rs:335:48
    |
335 |     fn with_friend_state(fs: Vec<FriendState>, randb: Vec<u8>) {
    |                                                ^^^^^
```

That part of the test was removed, so this also needs to go.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 19:46 UTC, kurnevsky commented
*[src/toxcore/dht.rs, line 362 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KukJoHHVVjLzDMM1GKM:-KuziX38OZqnJ-9uYjcD:b-896fix) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/dht.rs#L362)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

I think that the function name should better reflect what the function is for, in this case it probably should be renamed to `as_ipv4_packed_node`. Since there are only 2 places where function is called, there's no real benefit in shortening its name, and there's a minus side of making it a bit more confusing by obfuscating its name.

Earlier this function name was inside of the parsing function, and as the function could be used only inside the parsing function having short name was still fine. As it is now accessible for use by more than just the parsing function, it should have a better name.

Also, since function is used only in the FromBytes implementation of PackedNode the comment above the function should state that it is intended to be used only there.

Same goes for the corresponding IPv6 function name.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 19:46 UTC, kurnevsky commented
*[src/toxcore/dht.rs, line 361 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KukKky3xYeGhrpuINmK:-KuziYqohLki9JZwoesw:b-896fix) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/dht.rs#L361)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

This comment is rather misleading if someone doesn't look at the code below – instead of saying that bytes are parsed as an IPv4 address, it should say that bytes are parsed as an IPv4 type of PackedNode: `Parse bytes as an IPv4 PackedNode`.

Same goes for the comment for corresponding IPv6 function comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 19:52 UTC, kurnevsky commented
*[src/toxcore/toxid.rs, line 112 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KukUITyACrCL2d3yd6n:-KuzjxfPDKPNWQQDGRUn:b-896fix) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/toxid.rs#L112)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Curly brackets (`{}`) aren't needed?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 19:53 UTC, kurnevsky commented
*[src/toxcore/toxid.rs, line 257 at r1](https://reviewable.io:443/reviews/zetok/tox/51#-KtGAfaGjQdkBD_dVhTb-r1-257:-Kuzjz-9jWUpYH6wFxk7:b-896fix) ([raw file](https://github.com/zetok/tox/blob/eb7693839011d3f1fad6c090538e11068ab71b7f/src/toxcore/toxid.rs#L257)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Probably. @kurnevsky mind adding?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 19:57 UTC, kurnevsky commented
*[src/toxcore/state_format/old.rs, line 1354 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-Kuo9iBUSmM7EXVNBj67:-Kuzl35mOxNEww6n12D7:b-896fix) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/state_format/old.rs#L1354)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Since test macro is no longer used in the fn, the `cfg` line can be removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 19:57 UTC, kurnevsky commented
*[src/toxcore/state_format/old.rs, line 1571 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoAcNOKXU0bewKfcFx:-Kuzl4qaE1vNPB3kcYQm:b-896fix) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/state_format/old.rs#L1571)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Same as above, line can be removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 19:57 UTC, kurnevsky commented
*[src/toxcore/state_format/old.rs, line 1675 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoBQjHIK66Nb-byXM7:-Kuzl6CqGibA2Hc8rz64:b-896fix) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/state_format/old.rs#L1675)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Same as above, line can be removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 20:00 UTC, kurnevsky commented
*[src/toxcore/state_format/old.rs, line 1173 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoCX9684KjgjYVmZYY:-Kuzlir3Ld9NbYz8x15y:b-896fix) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/state_format/old.rs#L1173)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Well, if it is used in tests only, you may move it in tests
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 20:01 UTC, kurnevsky commented
*[src/toxcore/state_format/old.rs, line 24 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoCw2PH7GZ6GpC18JF:-KuzlnNEz5EaOxCUISr8:b-896fix) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/state_format/old.rs#L24)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

```
warning: unused import: `ByteOrder`, #[warn(unused_imports)] on by default
  --> src/toxcore/state_format/old.rs:24:28
   |
24 | use byteorder::{BigEndian, ByteOrder, LittleEndian, WriteBytesExt};
   |                            ^^^^^^^^^
```

Still used in tests, but when building without tests produces a warning
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 20:29 UTC, kurnevsky commented
*[src/toxcore/binary_io.rs, line 42 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoDZQxJskQj_0tABU1:-Kuzs2T__31rQyLCuWki:bjhbr6) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/binary_io.rs#L42)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

Or you may try `named_attr` to create function with docs
</blockquote></details>

reimplemented with closure! macro. Now it looks weird but at least compiles without warnings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 20:29 UTC, kurnevsky commented
*[src/toxcore/binary_io.rs, line 46 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoDsS7NaxVSbe5IGXq:-KuzsO6FLruQTVJWnFOg:b-jjw2dk) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/binary_io.rs#L46)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

```
warning: missing documentation for a trait method
  --> src/toxcore/binary_io.rs:46:5
   |
46 |     named_args!(parse_bytes_multiple_n(times: usize) <Vec<Self>>, many_m_n!(times, times, Self::parse_bytes));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro outside of the current crate
```

Same as above.
</blockquote></details>

reimplemented with closure! macro.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 20:32 UTC, kurnevsky commented
Everything alright now?

2017-09-26 20:36 UTC, kpp commented
Reviewed 1 of 8 files at r7.
Review status: 12 of 18 files reviewed at latest revision, 16 unresolved discussions.

---

*[src/toxcore/binary_io.rs, line 42 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoDZQxJskQj_0tABU1:-KuztgU9DUbQBf1OUX6f:b-ac7guh) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/binary_io.rs#L42)):*
<details><summary><i>Previously, kurnevsky (Evgeny Kurnevsky) wrote…</i></summary><blockquote>

reimplemented with closure! macro. Now it looks weird but at least compiles without warnings.
</blockquote></details>

I told you use `named_attr!` from nom.

```
// Create my_function as if you wrote it with the doc comment /// My Func
named_attr!(#[doc = "My Func"], my_function( &[u8] ) -> &[u8], tag!("abcd"));
// Also works for pub functions, and multiple lines
named!(#[doc = "My Func\nRecognise abcd"], pub my_function, tag!("abcd"));
// Multiple attributes can be passed if required
named!(#[doc = "My Func"] #[inline(always)], pub my_function, tag!("abcd"));
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-26 21:08 UTC, kurnevsky commented
*[src/toxcore/binary_io.rs, line 42 at r6](https://reviewable.io:443/reviews/zetok/tox/51#-KuoDZQxJskQj_0tABU1:-Kv--yNHvOjoa6uikIGH:b79m57b) ([raw file](https://github.com/zetok/tox/blob/caeede48d031bf22d0716dc5a97f7191895388de/src/toxcore/binary_io.rs#L42)):*
<details><summary><i>Previously, kpp (Roman) wrote…</i></summary><blockquote>

I told you use `named_attr!` from nom.

```
// Create my_function as if you wrote it with the doc comment /// My Func
named_attr!(#[doc = "My Func"], my_function( &[u8] ) -> &[u8], tag!("abcd"));
// Also works for pub functions, and multiple lines
named!(#[doc = "My Func\nRecognise abcd"], pub my_function, tag!("abcd"));
// Multiple attributes can be passed if required
named!(#[doc = "My Func"] #[inline(always)], pub my_function, tag!("abcd"));
```
</blockquote></details>

It's not possible to use named_attr! macro for parse_bytes_multiple_n becouse named_attr! can't take additional arguments. So let it be uniformly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51)*
<!-- Sent from Reviewable.io -->

2017-09-27 09:45 UTC, zetok commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 2 of 18 files at r4, 7 of 8 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zetok/tox/51#-:-Kv1iA5GFrt2qrTXMYl_:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-09-27 09:48 UTC, merged